// AUTO-GENERATED FROM schemas/tender_qualification.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/tender_qualification.schema.json — edit the JSON, regenerate.

/**
 * A go/no-go screening decision for a remedial-building tender, captured at the moment it lands — before a customer, job, or contract record exists in EQ. One record per tender, not a batch. The write target is a decision (price / walk / needs_review) with a reasoning trail, not a job record. Sits outside the canonical staff/site/asset spine deliberately: no customer/site/contact FK is required because this is pre-sale.
 */
export interface TenderQualification {
  /**
   * Primary key. Minted client-side or by eq_intake_commit_qualification on first save.
   */
  qualification_id: string;
  tenant_id: string;
  /**
   * The prospective client's name as it appears on the tender documents. Free text, no FK — no customer row exists yet at qualification time.
   */
  customer_name_raw?: string | null;
  /**
   * The tender's named contact (name / role / phone / email as extracted), free text. No contact FK — pre-sale.
   */
  contact_raw?: string | null;
  /**
   * The site or project address as it appears on the tender documents. Free text, no site FK.
   */
  site_address_raw?: string | null;
  /**
   * Vision-extracted plain-language summary of the scope of works from the contract + spec documents.
   */
  scope_summary?: string | null;
  /**
   * Estimated total contract value in AUD, extracted or manually entered. Feeds the margin and cash-flow factors.
   */
  contract_value_estimate?: number | null;
  /**
   * Estimated margin percentage after all costs, BEFORE any optimistic variations are assumed. Compared against the tenant's configured minimum in the go/no-go margin factor.
   */
  margin_estimate_pct?: number | null;
  /**
   * The 8-factor go/no-go matrix (business plan §8), one entry per factor. Shape: { "<factor>": { "answer": "preferred"|"no_go"|"needs_review", "confidence": 0.0-1.0, "source": "extracted"|"manual", "notes": string|null } }. An unanswerable factor MUST be recorded as needs_review, never silently defaulted to preferred (EQ-AS-CONDUIT rule #11) — mirrors the cycle_costs JSONB pattern already used in contract_scope.
   */
  risk_answers?: {
    client?: FactorAnswer;
    scope?: FactorAnswer;
    margin?: FactorAnswer;
    cash_flow?: FactorAnswer;
    contract?: FactorAnswer;
    program?: FactorAnswer;
    technical?: FactorAnswer;
    location?: FactorAnswer;
  };
  /**
   * The go/no-go outcome. null while the qualification is still a draft with no decision run yet.
   */
  decision?: "price" | "walk" | "needs_review" | null;
  /**
   * The reasoning trail behind `decision` — ALWAYS populated whenever decision is set, never just the label (EQ-AS-CONDUIT rule #11 / plan §C.1). Typically the joined per-factor reasons from the rules.ts evaluator.
   */
  decision_reason?: string | null;
  /**
   * The user who ran or confirmed the decision. Null for an unattended/system-only evaluation.
   */
  decision_made_by?: string | null;
  decision_made_at?: string | null;
  /**
   * Self-contained audit trail of the documents this qualification was extracted from — contract, spec, photos.
   */
  source_files?: {
    file_name: string;
    sha256?: string | null;
    size_bytes?: number | null;
    kind?: "contract" | "spec" | "photo" | "other" | null;
  }[];
  /**
   * Import/decision lifecycle. 'draft' = still being answered. 'decided' = a decision has been recorded. 'archived' = withdrawn/superseded — the only form of rollback (a plain status update; there is no delete RPC).
   */
  status: "draft" | "decided" | "archived";
  schema_version?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
  created_by?: string | null;
  updated_by?: string | null;
}
export interface FactorAnswer {
  /**
   * needs_review means the factor could not be confidently answered — it is the explicit non-silent default, never omitted in place of a guess.
   */
  answer: "preferred" | "no_go" | "needs_review";
  /**
   * 0.0-1.0. Null for a manually-answered factor where confidence isn't meaningful.
   */
  confidence?: number | null;
  source: "extracted" | "manual";
  notes?: string | null;
}
